
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  The Maisey Service reports on the status of my dog.

Transform:
- AWS::Serverless-2016-10-31

Resources:
  maiseyStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: maisey_service
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Description: Maisey is a good girl (most of the time).
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
